In [93]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [94]:
dataset = pd.read_excel(r'C:\Users\DELL\OneDrive\Desktop\Date_Fruit_Datasets.xlsx')

In [95]:
dataset

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0    422163  2378.9080    837.8484    645.6693        0.6373  733.1539   
1    338136  2085.1440    723.8198    595.2073        0.5690  656.1464   
2    526843  2647.3940    940.7379    715.3638        0.6494  819.0222   
3    416063  2351.2100    827.9804    645.2988        0.6266  727.8378   
4    347562  2160.3540    763.9877    582.8359        0.6465  665.2291   
..      ...        ...         ...         ...           ...       ...   
893  255403  1925.3650    691.8453    477.1796        0.7241  570.2536   
894  365924  2664.8230    855.4633    551.5447        0.7644  682.5752   
895  254330  1926.7360    747.4943    435.6219        0.8126  569.0545   
896  238955  1906.2679    716.6485    441.8297        0.7873  551.5859   
897  343792  2289.2720    823.8438    534.7757        0.7607  661.6113   

     SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  KurtosisRR  KurtosisRG  \
0      0.9947       424428  0.7831        1.2976  ...      3.2370      2.9574   
1      0.9974       339014  0.7795        1.2161  ...      2.6228      2.6350   
2      0.9962       528876  0.7657        1.3150  ...      3.7516      3.8611   
3      0.9948       418255  0.7759        1.2831  ...      5.0401      8.6136   
4      0.9908       350797  0.7569        1.3108  ...      2.7016      2.9761   
..        ...          ...     ...           ...  ...         ...         ...   
893    0.9785       261028  0.7269        1.4499  ...      2.2423      2.3704   
894    0.9466       386566  0.6695        1.5510  ...      3.4109      3.5805   
895    0.9925       256255  0.7240        1.7159  ...      2.2759      2.5090   
896    0.9604       248795  0.6954        1.6220  ...      2.6769      2.6874   
897    0.9781       351472  0.6941        1.5405  ...      2.5138      3.0369   

     KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  \
0        4.2287 -59191263232 -50714214400 -39922372608     58.7255   
1        3.1704 -34233065472 -37462601728 -31477794816     50.0259   
2        4.7192 -93948354560 -74738221056 -60311207936     65.4772   
3        8.2618 -32074307584 -32060925952 -29575010304     43.3900   
4        4.4146 -39980974080 -35980042240 -25593278464     52.7743   
..          ...          ...          ...          ...         ...   
893      2.7202 -25296416768 -19168882688 -18473392128     49.0869   
894      3.9910 -31605219328 -21945366528 -19277905920     46.8086   
895      2.6951 -22242772992 -19594921984 -17592152064     44.1325   
896      2.7991 -26048595968 -21299822592 -19809978368     51.2267   
897      3.0865 -31983476736 -20482514944 -21219354624     47.3454   

     ALLdaub4RG  ALLdaub4RB  Class  
0       54.9554     47.8400  BERHI  
1       52.8168     47.8315  BERHI  
2       59.2860     51.9378  BERHI  
3       44.1259     41.1882  BERHI  
4       50.9080     42.6666  BERHI  
..          ...         ...    ...  
893     43.0422     42.4153  SOGAY  
894     39.1046     36.5502  SOGAY  
895     40.7986     40.9769  SOGAY  
896     45.7162     45.6260  SOGAY  
897     38.6966     39.6738  SOGAY  

[898 rows x 35 columns]

In [96]:
value = dataset["Class"].value_counts().to_dict()

In [97]:
value

{'DOKOL': 204,
 'SAFAVI': 199,
 'ROTANA': 166,
 'DEGLET': 98,
 'SOGAY': 94,
 'IRAQI': 72,
 'BERHI': 65}

In [98]:
value1 = {'DOKOL': 0,
 'SAFAVI': 1,
 'ROTANA': 2,
 'DEGLET': 3,
 'SOGAY': 4,
 'IRAQI': 5,
 'BERHI': 6}

In [99]:
dataset["Class"] = dataset["Class"].map(value1)

In [100]:
dataset

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0    422163  2378.9080    837.8484    645.6693        0.6373  733.1539   
1    338136  2085.1440    723.8198    595.2073        0.5690  656.1464   
2    526843  2647.3940    940.7379    715.3638        0.6494  819.0222   
3    416063  2351.2100    827.9804    645.2988        0.6266  727.8378   
4    347562  2160.3540    763.9877    582.8359        0.6465  665.2291   
..      ...        ...         ...         ...           ...       ...   
893  255403  1925.3650    691.8453    477.1796        0.7241  570.2536   
894  365924  2664.8230    855.4633    551.5447        0.7644  682.5752   
895  254330  1926.7360    747.4943    435.6219        0.8126  569.0545   
896  238955  1906.2679    716.6485    441.8297        0.7873  551.5859   
897  343792  2289.2720    823.8438    534.7757        0.7607  661.6113   

     SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  KurtosisRR  KurtosisRG  \
0      0.9947       424428  0.7831        1.2976  ...      3.2370      2.9574   
1      0.9974       339014  0.7795        1.2161  ...      2.6228      2.6350   
2      0.9962       528876  0.7657        1.3150  ...      3.7516      3.8611   
3      0.9948       418255  0.7759        1.2831  ...      5.0401      8.6136   
4      0.9908       350797  0.7569        1.3108  ...      2.7016      2.9761   
..        ...          ...     ...           ...  ...         ...         ...   
893    0.9785       261028  0.7269        1.4499  ...      2.2423      2.3704   
894    0.9466       386566  0.6695        1.5510  ...      3.4109      3.5805   
895    0.9925       256255  0.7240        1.7159  ...      2.2759      2.5090   
896    0.9604       248795  0.6954        1.6220  ...      2.6769      2.6874   
897    0.9781       351472  0.6941        1.5405  ...      2.5138      3.0369   

     KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  \
0        4.2287 -59191263232 -50714214400 -39922372608     58.7255   
1        3.1704 -34233065472 -37462601728 -31477794816     50.0259   
2        4.7192 -93948354560 -74738221056 -60311207936     65.4772   
3        8.2618 -32074307584 -32060925952 -29575010304     43.3900   
4        4.4146 -39980974080 -35980042240 -25593278464     52.7743   
..          ...          ...          ...          ...         ...   
893      2.7202 -25296416768 -19168882688 -18473392128     49.0869   
894      3.9910 -31605219328 -21945366528 -19277905920     46.8086   
895      2.6951 -22242772992 -19594921984 -17592152064     44.1325   
896      2.7991 -26048595968 -21299822592 -19809978368     51.2267   
897      3.0865 -31983476736 -20482514944 -21219354624     47.3454   

     ALLdaub4RG  ALLdaub4RB  Class  
0       54.9554     47.8400      6  
1       52.8168     47.8315      6  
2       59.2860     51.9378      6  
3       44.1259     41.1882      6  
4       50.9080     42.6666      6  
..          ...         ...    ...  
893     43.0422     42.4153      4  
894     39.1046     36.5502      4  
895     40.7986     40.9769      4  
896     45.7162     45.6260      4  
897     38.6966     39.6738      4  

[898 rows x 35 columns]

In [101]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   AREA           898 non-null    int64  
 1   PERIMETER      898 non-null    float64
 2   MAJOR_AXIS     898 non-null    float64
 3   MINOR_AXIS     898 non-null    float64
 4   ECCENTRICITY   898 non-null    float64
 5   EQDIASQ        898 non-null    float64
 6   SOLIDITY       898 non-null    float64
 7   CONVEX_AREA    898 non-null    int64  
 8   EXTENT         898 non-null    float64
 9   ASPECT_RATIO   898 non-null    float64
 10  ROUNDNESS      898 non-null    float64
 11  COMPACTNESS    898 non-null    float64
 12  SHAPEFACTOR_1  898 non-null    float64
 13  SHAPEFACTOR_2  898 non-null    float64
 14  SHAPEFACTOR_3  898 non-null    float64
 15  SHAPEFACTOR_4  898 non-null    float64
 16  MeanRR         898 non-null    float64
 17  MeanRG         898 non-null    float64
 18  MeanRB    

In [102]:
dataset.isna().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [103]:
#split data into X and y
X = dataset.drop("Class" , axis =1 ).astype(float)
y = dataset["Class"]

In [104]:
X

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0    422163.0  2378.9080    837.8484    645.6693        0.6373  733.1539   
1    338136.0  2085.1440    723.8198    595.2073        0.5690  656.1464   
2    526843.0  2647.3940    940.7379    715.3638        0.6494  819.0222   
3    416063.0  2351.2100    827.9804    645.2988        0.6266  727.8378   
4    347562.0  2160.3540    763.9877    582.8359        0.6465  665.2291   
..        ...        ...         ...         ...           ...       ...   
893  255403.0  1925.3650    691.8453    477.1796        0.7241  570.2536   
894  365924.0  2664.8230    855.4633    551.5447        0.7644  682.5752   
895  254330.0  1926.7360    747.4943    435.6219        0.8126  569.0545   
896  238955.0  1906.2679    716.6485    441.8297        0.7873  551.5859   
897  343792.0  2289.2720    823.8438    534.7757        0.7607  661.6113   

     SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  SkewRB  KurtosisRR  \
0      0.9947     424428.0  0.7831        1.2976  ...  0.6019      3.2370   
1      0.9974     339014.0  0.7795        1.2161  ...  0.4134      2.6228   
2      0.9962     528876.0  0.7657        1.3150  ...  0.9183      3.7516   
3      0.9948     418255.0  0.7759        1.2831  ...  1.8028      5.0401   
4      0.9908     350797.0  0.7569        1.3108  ...  0.8865      2.7016   
..        ...          ...     ...           ...  ...     ...         ...   
893    0.9785     261028.0  0.7269        1.4499  ... -0.1398      2.2423   
894    0.9466     386566.0  0.6695        1.5510  ...  0.5611      3.4109   
895    0.9925     256255.0  0.7240        1.7159  ...  0.2665      2.2759   
896    0.9604     248795.0  0.6954        1.6220  ...  0.5325      2.6769   
897    0.9781     351472.0  0.6941        1.5405  ...  0.4318      2.5138   

     KurtosisRG  KurtosisRB     EntropyRR     EntropyRG     EntropyRB  \
0        2.9574      4.2287 -5.919126e+10 -5.071421e+10 -3.992237e+10   
1        2.6350      3.1704 -3.423307e+10 -3.746260e+10 -3.147779e+10   
2        3.8611      4.7192 -9.394835e+10 -7.473822e+10 -6.031121e+10   
3        8.6136      8.2618 -3.207431e+10 -3.206093e+10 -2.957501e+10   
4        2.9761      4.4146 -3.998097e+10 -3.598004e+10 -2.559328e+10   
..          ...         ...           ...           ...           ...   
893      2.3704      2.7202 -2.529642e+10 -1.916888e+10 -1.847339e+10   
894      3.5805      3.9910 -3.160522e+10 -2.194537e+10 -1.927791e+10   
895      2.5090      2.6951 -2.224277e+10 -1.959492e+10 -1.759215e+10   
896      2.6874      2.7991 -2.604860e+10 -2.129982e+10 -1.980998e+10   
897      3.0369      3.0865 -3.198348e+10 -2.048251e+10 -2.121935e+10   

     ALLdaub4RR  ALLdaub4RG  ALLdaub4RB  
0       58.7255     54.9554     47.8400  
1       50.0259     52.8168     47.8315  
2       65.4772     59.2860     51.9378  
3       43.3900     44.1259     41.1882  
4       52.7743     50.9080     42.6666  
..          ...         ...         ...  
893     49.0869     43.0422     42.4153  
894     46.8086     39.1046     36.5502  
895     44.1325     40.7986     40.9769  
896     51.2267     45.7162     45.6260  
897     47.3454     38.6966     39.6738  

[898 rows x 34 columns]

In [105]:
y

0      6
1      6
2      6
3      6
4      6
      ..
893    4
894    4
895    4
896    4
897    4
Name: Class, Length: 898, dtype: int64

In [106]:
y.value_counts()

0    204
1    199
2    166
3     98
4     94
5     72
6     65
Name: Class, dtype: int64

In [107]:
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder

In [108]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
y = np_utils.to_categorical(encoded_Y)

In [109]:
encoded_Y

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [110]:
y[1:5]

array([[0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [112]:
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [113]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [114]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [115]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout
from keras.layers import Activation, Dense

In [119]:
def create_model(layers, activation):
    model = Sequential()
    for i, nodes in enumerate(layers):
        if i==0:
            model.add(Dense(nodes,input_dim=X_train.shape[1]))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:
            model.add(Dense(nodes))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
            
    model.add(Dense(units = 7, kernel_initializer= 'glorot_uniform', activation = 'softmax')) # Note: no activation beyond this point
    
    model.compile(optimizer='adam', loss='CategoricalCrossentropy',metrics=['accuracy'])
    return model

In [120]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
model = KerasClassifier(build_fn=create_model, verbose=0)


layers = [ [120],[250], [500] , [500,250]]
activations = ['sigmoid', 'Relu']
param_grid = dict(layers=layers, activation=activations, batch_size = [70 ,128, 256], epochs=[100])
grid = GridSearchCV(estimator=model, param_grid=param_grid,cv=5)

<ipython-input-120-9bd6f8310d70>:3: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  model = KerasClassifier(build_fn=create_model, verbose=0)


In [121]:
grid_result = grid.fit(X_train, y_train)

c:\users\dell\documents\sample_project\env\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
60 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "c:\users\dell\documents\sample_project\env\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\users\dell\documents\sample_project\env\lib\site-packages\keras\wrappers\scikit_learn.py", line 236, in fit
    return super(KerasClassifier, self).fit(x, y, **kwargs)
  File "c:\users\dell\documents\sample_project\env\lib\site-packages\keras\wrappers\scikit_lea

In [122]:
grid_result.best_score_

0.9060190439224243

In [123]:
# Predicting the Test set results
y_pred = grid_result.predict(X_test)

9/9 [==============================] - 0s 3ms/step


In [124]:
y_pred

array([1, 6, 5, 6, 0, 2, 2, 2, 1, 0, 2, 0, 2, 0, 4, 4, 0, 1, 1, 1, 6, 1,
       0, 0, 0, 4, 1, 1, 5, 3, 1, 5, 1, 2, 1, 0, 2, 1, 4, 5, 1, 1, 4, 2,
       6, 3, 2, 2, 1, 4, 4, 0, 0, 4, 0, 1, 3, 2, 0, 3, 0, 0, 5, 2, 5, 4,
       1, 1, 0, 0, 1, 2, 1, 1, 3, 0, 3, 0, 2, 1, 0, 6, 2, 3, 1, 0, 6, 0,
       5, 1, 4, 1, 4, 0, 1, 5, 1, 5, 2, 3, 3, 4, 0, 0, 1, 2, 1, 3, 1, 1,
       2, 1, 1, 0, 0, 4, 4, 5, 2, 1, 0, 1, 0, 0, 0, 0, 5, 1, 2, 6, 1, 2,
       1, 3, 0, 4, 1, 0, 5, 5, 1, 3, 4, 6, 1, 2, 6, 0, 5, 5, 2, 4, 4, 4,
       1, 0, 1, 1, 0, 2, 6, 3, 1, 0, 0, 3, 0, 0, 1, 2, 2, 0, 2, 3, 0, 3,
       5, 0, 0, 2, 1, 4, 6, 1, 1, 1, 4, 0, 0, 5, 3, 3, 0, 5, 0, 0, 0, 2,
       1, 3, 2, 6, 2, 2, 2, 0, 2, 2, 6, 6, 0, 2, 2, 1, 2, 5, 6, 1, 0, 6,
       0, 3, 2, 0, 1, 6, 1, 4, 0, 1, 0, 2, 0, 0, 2, 5, 0, 6, 0, 3, 5, 2,
       1, 2, 2, 2, 2, 0, 6, 4, 4, 5, 0, 1, 0, 3, 4, 3, 1, 6, 4, 2, 0, 3,
       6, 2, 2, 0, 3, 3])

In [128]:
y_test[1:10]

array([[0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [129]:
y_new = np.argmax(y_test, axis=-1)
print(y_new)


[1 6 5 6 0 2 2 2 1 0 5 0 2 0 4 4 0 4 1 1 6 1 0 0 0 4 1 1 5 0 1 5 1 2 1 0 2
 1 4 5 1 1 4 2 6 3 2 2 1 3 2 0 0 4 0 1 3 2 0 4 0 0 5 2 5 4 1 1 0 0 1 6 1 1
 4 0 3 3 2 1 0 6 2 3 1 3 6 0 6 1 4 1 4 0 4 5 1 5 2 3 4 4 0 0 1 2 1 3 1 1 2
 1 1 0 0 4 4 5 2 1 0 1 0 0 0 3 5 1 2 6 1 2 1 3 0 4 1 0 5 5 1 3 4 6 1 2 6 0
 5 5 2 4 4 4 1 0 1 1 0 2 6 3 1 0 0 4 0 0 1 2 2 0 2 3 0 3 5 0 0 2 1 4 6 1 1
 1 4 0 0 5 3 4 0 5 0 0 0 2 1 3 2 5 2 2 2 1 2 2 6 6 0 2 2 1 2 5 6 1 0 6 0 3
 2 0 1 6 1 4 0 1 3 2 0 0 2 5 0 6 3 3 5 2 1 2 2 2 2 0 6 4 4 5 0 1 0 3 4 4 1
 6 4 2 0 3 6 2 2 0 3 3]


In [135]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_new, y_pred)

In [136]:
cm

array([[61,  0,  0,  1,  0,  0,  0],
       [ 1, 57,  0,  0,  0,  0,  0],
       [ 0,  0, 47,  0,  1,  0,  0],
       [ 5,  0,  0, 19,  1,  0,  0],
       [ 0,  2,  0,  6, 24,  0,  0],
       [ 0,  0,  1,  0,  0, 21,  1],
       [ 0,  0,  1,  0,  0,  1, 20]], dtype=int64)

In [137]:

print("Classification report: {}".format(classification_report(y_new,y_pred)))

Classification report:               precision    recall  f1-score   support

           0       0.91      0.98      0.95        62
           1       0.97      0.98      0.97        58
           2       0.96      0.98      0.97        48
           3       0.73      0.76      0.75        25
           4       0.92      0.75      0.83        32
           5       0.95      0.91      0.93        23
           6       0.95      0.91      0.93        22

    accuracy                           0.92       270
   macro avg       0.91      0.90      0.90       270
weighted avg       0.92      0.92      0.92       270



In [138]:
grid_result.best_params_

{'activation': 'sigmoid', 'batch_size': 70, 'epochs': 100, 'layers': [250]}

In [142]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_new)

In [143]:
score

0.9222222222222223